//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaveYouSeeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageID { get; set; }
        public int UserId { get; set; }
        public System.DateTime MessageDate { get; set; }
        public string From { get; set; }
        public string Email { get; set; }
        public string Subjet { get; set; }
        public string Message1 { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
