//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaveYouSeeMe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetPhoto
    {
        public int PhotoID { get; set; }
        public int PetID { get; set; }
        public string Photo { get; set; }
        public string Notes { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
